Created slurm-controller grpc communication. To be fixed

diff --git a/operators/build/golang-grpc-common/client/Dockerfile b/operators/build/golang-grpc-common/client/Dockerfile
--- a/operators/build/golang-grpc-common/client/Dockerfile
+++ b/operators/build/golang-grpc-common/client/Dockerfile
@@ -11,10 +11,12 @@ RUN go mod download && go mod verify
 
 # Set which component to be installed
 ARG COMPONENT
-RUN test -n "$COMPONENT" || ( echo "The COMPONENT argument is unset. Aborting" && false )
+ARG DOMAIN
+RUN test -n "$COMPONENT" || ( echo "The COMPONENT argument is unset. Aborting" && false ) && \
+    test -n "$DOMAIN" || ( echo "The DOMAIN argument is unset. Aborting" && false )
 
 COPY . ./
-RUN CGO_ENABLED=0 GOOS=linux GOARCH=$(go env GOARCH) go build -ldflags="-s -w" ./cmd/$COMPONENT/client
+RUN CGO_ENABLED=0 GOOS=linux GOARCH=$(go env GOARCH) go build -ldflags="-s -w -X main.domain=$DOMAIN" ./cmd/$COMPONENT/grpc/client
 
 ###
 
@@ -24,8 +26,10 @@ RUN apk update
 
 ARG COMPONENT
 
-COPY --from=builder /tmp/builder/client /usr/bin/$COMPONENT
+COPY --from=builder /tmp/builder/client /usr/bin/client
+COPY --from=builder /tmp/builder/test/sbatch/test_script.sh /usr/bin/test_script.sh
 
-RUN ln -s /usr/bin/$COMPONENT /usr/bin/bioeda-component
+RUN ln -s /usr/bin/client /usr/bin/bioeda-component
 
-ENTRYPOINT [ "/usr/bin/bioeda-component" ]
+# ENTRYPOINT [ "/usr/bin/bioeda-component" ]
+# CMD ["-filepath /usr/bin/test_script.sh"]
